import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Providers } from "@/store/provider";
import "tailwindcss/tailwind.css";
import NavBar from "@/components/ui/nav-barr";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeProvider
            attribute="class"
            enableSystem={true}
            defaultTheme="system"
          >
            <NavBar />
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
