import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { Providers } from "@/hooks/providers";
/* import DynamicAlert from "@/components/ui/dynamic-alert";*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        {children}
        <SpeedInsights />
        <Providers>
          <></>
          {/* <DynamicAlert />*/}
        </Providers>
      </body>
    </html>
  );
}
